import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#e0e2eb",
        "on-surface-variant": "#c7c6cc",
        "on-primary-container": "#777b8a",
        "on-primary": "#2c303d",
        "on-tertiary-fixed-variant": "#004e5c",
        secondary: "#adc6ff",
        "surface-container-lowest": "#0b0e14",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#e6ecff",
        "on-tertiary": "#003640",
        "on-primary-fixed-variant": "#434654",
        "primary-fixed": "#dfe2f3",
        "on-secondary": "#002e6a",
        "surface-bright": "#363940",
        "inverse-surface": "#e0e2eb",
        "surface-container-high": "#262a31",
        "inverse-on-surface": "#2d3137",
        "tertiary-container": "#001116",
        "glass-border": "rgba(255, 255, 255, 0.08)",
        "surface-container-highest": "#31353c",
        "on-error": "#690005",
        outline: "#909096",
        "surface-container": "#1c2026",
        "surface-dim": "#101419",
        "surface-tint": "#c3c6d7",
        "primary-container": "#0a0e1a",
        background: "#101419",
        tertiary: "#4cd7f6",
        "outline-variant": "#46464c",
        "on-background": "#e0e2eb",
        "midnight-deep": "#0A0E1A",
        "on-secondary-fixed": "#001a42",
        "obsidian-base": "#020408",
        "secondary-fixed-dim": "#adc6ff",
        "inverse-primary": "#5a5e6d",
        "tertiary-fixed": "#acedff",
        "surface-container-low": "#181c22",
        surface: "#101419",
        "electric-glow": "#3B82F6",
        "on-primary-fixed": "#171b28",
        primary: "#c3c6d7",
        "silver-particle": "#E2E8F0",
        "secondary-container": "#0566d9",
        "on-secondary-fixed-variant": "#004395",
        "tertiary-fixed-dim": "#4cd7f6",
        "surface-variant": "#31353c",
        "primary-fixed-dim": "#c3c6d7",
        "on-tertiary-fixed": "#001f26",
        "cyan-pulse": "#06B6D4",
        "secondary-fixed": "#d8e2ff",
        "on-tertiary-container": "#00879e",
        "error-container": "#93000a",
        error: "#ffb4ab",
      },
      borderRadius: {
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "20px",
        "3xl": "24px",
        full: "9999px",
      },
      spacing: {
        gutter: "32px",
        "margin-desktop": "64px",
        unit: "4px",
        "margin-mobile": "24px",
        "section-gap": "clamp(3rem, 8vh, 6rem)",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "display-xl": ["Geist", "sans-serif"],
        "mono-data": ["Geist Mono", "monospace"],
      },
      fontSize: {
        // Fluid type scale — no overflow, no giant movie poster text
        "display-xl": ["clamp(2rem, 5vw, 3.5rem)", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-lg": ["clamp(1.5rem, 3vw, 2.25rem)", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["clamp(1.125rem, 2vw, 1.5rem)", { lineHeight: "1.3", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-lg": ["clamp(1rem, 1.5vw, 1.125rem)", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["0.9375rem", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["0.75rem", { lineHeight: "1.2", letterSpacing: "0.12em", fontWeight: "600" }],
        "mono-data": ["0.875rem", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "500" }],
      },
      animation: {
        "scan-down": "scanDown 4s linear infinite",
        "fade-in": "fadeIn 0.6s ease-out forwards",
        "slide-up": "slideUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "pulse-glow": "pulseGlow 2s ease-in-out infinite",
      },
      keyframes: {
        scanDown: {
          "0%": { transform: "translateY(-100%)", opacity: "0" },
          "20%": { opacity: "1" },
          "80%": { opacity: "1" },
          "100%": { transform: "translateY(200vh)", opacity: "0" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(24px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        pulseGlow: {
          "0%, 100%": { boxShadow: "0 0 20px rgba(6,182,212,0.3)" },
          "50%": { boxShadow: "0 0 40px rgba(6,182,212,0.7)" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
